// Maps common Italian country names to the English names used by the
// world-atlas boundaries dataset, so visited countries can be matched
// against the geojson features on the travel globe.
export const IT_TO_EN_COUNTRY: Record<string, string> = {
  "italia": "Italy",
  "francia": "France",
  "germania": "Germany",
  "spagna": "Spain",
  "portogallo": "Portugal",
  "regno unito": "United Kingdom",
  "inghilterra": "United Kingdom",
  "irlanda": "Ireland",
  "olanda": "Netherlands",
  "paesi bassi": "Netherlands",
  "belgio": "Belgium",
  "lussemburgo": "Luxembourg",
  "svizzera": "Switzerland",
  "austria": "Austria",
  "grecia": "Greece",
  "polonia": "Poland",
  "repubblica ceca": "Czechia",
  "cechia": "Czechia",
  "slovacchia": "Slovakia",
  "ungheria": "Hungary",
  "slovenia": "Slovenia",
  "croazia": "Croatia",
  "bosnia": "Bosnia and Herzegovina",
  "serbia": "Serbia",
  "montenegro": "Montenegro",
  "albania": "Albania",
  "macedonia del nord": "North Macedonia",
  "romania": "Romania",
  "bulgaria": "Bulgaria",
  "danimarca": "Denmark",
  "svezia": "Sweden",
  "norvegia": "Norway",
  "finlandia": "Finland",
  "islanda": "Iceland",
  "estonia": "Estonia",
  "lettonia": "Latvia",
  "lituania": "Lithuania",
  "russia": "Russia",
  "ucraina": "Ukraine",
  "malta": "Malta",
  "monaco": "Monaco",
  "cipro": "Cyprus",
  "turchia": "Turkey",
  "marocco": "Morocco",
  "tunisia": "Tunisia",
  "egitto": "Egypt",
  "stati uniti": "United States of America",
  "usa": "United States of America",
  "canada": "Canada",
  "messico": "Mexico",
  "brasile": "Brazil",
  "argentina": "Argentina",
  "cile": "Chile",
  "perù": "Peru",
  "peru": "Peru",
  "colombia": "Colombia",
  "giappone": "Japan",
  "cina": "China",
  "corea del sud": "South Korea",
  "thailandia": "Thailand",
  "vietnam": "Vietnam",
  "indonesia": "Indonesia",
  "india": "India",
  "emirati arabi uniti": "United Arab Emirates",
  "israele": "Israel",
  "sudafrica": "South Africa",
  "australia": "Australia",
  "nuova zelanda": "New Zealand",
};

export function toEnglishCountryName(name: string): string {
  const key = name.trim().toLowerCase();
  return IT_TO_EN_COUNTRY[key] ?? name.trim();
}
